/* Generated By:JJTree&JavaCC: Do not edit this line. AnalizadorConstants.java */
package Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 1;
  /** RegularExpression Id. */
  int RESTA = 2;
  /** RegularExpression Id. */
  int MULTI = 3;
  /** RegularExpression Id. */
  int DIV = 4;
  /** RegularExpression Id. */
  int POW = 5;
  /** RegularExpression Id. */
  int INCR = 6;
  /** RegularExpression Id. */
  int DECR = 7;
  /** RegularExpression Id. */
  int I_ASIG = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int DISTINTO = 10;
  /** RegularExpression Id. */
  int MENOR = 11;
  /** RegularExpression Id. */
  int MAYOR = 12;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 13;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int PAR_IZ = 18;
  /** RegularExpression Id. */
  int PAR_DER = 19;
  /** RegularExpression Id. */
  int COR_IZ = 20;
  /** RegularExpression Id. */
  int COR_Der = 21;
  /** RegularExpression Id. */
  int PUNTO_COMA = 22;
  /** RegularExpression Id. */
  int COMA = 23;
  /** RegularExpression Id. */
  int PUNTO = 24;
  /** RegularExpression Id. */
  int R_USAR = 25;
  /** RegularExpression Id. */
  int R_CREAR = 26;
  /** RegularExpression Id. */
  int R_BASE = 27;
  /** RegularExpression Id. */
  int R_TABLA = 28;
  /** RegularExpression Id. */
  int R_OBJETO = 29;
  /** RegularExpression Id. */
  int R_PROCEDIMIENTO = 30;
  /** RegularExpression Id. */
  int R_FUNCION = 31;
  /** RegularExpression Id. */
  int R_RETORNO = 32;
  /** RegularExpression Id. */
  int R_USUARIO = 33;
  /** RegularExpression Id. */
  int R_COLOCAR = 34;
  /** RegularExpression Id. */
  int R_PAS = 35;
  /** RegularExpression Id. */
  int R_IMPRIMIR = 36;
  /** RegularExpression Id. */
  int R_INSERTAR = 37;
  /** RegularExpression Id. */
  int R_EN = 38;
  /** RegularExpression Id. */
  int R_VALORES = 39;
  /** RegularExpression Id. */
  int R_ACTUALIZAR = 40;
  /** RegularExpression Id. */
  int R_DONDE = 41;
  /** RegularExpression Id. */
  int R_BORRAR = 42;
  /** RegularExpression Id. */
  int R_SELECCIONAR = 43;
  /** RegularExpression Id. */
  int R_DE = 44;
  /** RegularExpression Id. */
  int R_ORDENAR = 45;
  /** RegularExpression Id. */
  int R_ASC = 46;
  /** RegularExpression Id. */
  int R_DESC = 47;
  /** RegularExpression Id. */
  int R_OTORGAR = 48;
  /** RegularExpression Id. */
  int R_PERMISOS = 49;
  /** RegularExpression Id. */
  int R_DENEGAR = 50;
  /** RegularExpression Id. */
  int R_BACKUP = 51;
  /** RegularExpression Id. */
  int R_USQLDUMP = 52;
  /** RegularExpression Id. */
  int R_COMPLETO = 53;
  /** RegularExpression Id. */
  int R_RESTAURAR = 54;
  /** RegularExpression Id. */
  int R_ALTERAR = 55;
  /** RegularExpression Id. */
  int R_AGREGAR = 56;
  /** RegularExpression Id. */
  int R_QUITAR = 57;
  /** RegularExpression Id. */
  int R_CAMBIAR = 58;
  /** RegularExpression Id. */
  int R_ELIMINAR = 59;
  /** RegularExpression Id. */
  int R_DECLARAR = 60;
  /** RegularExpression Id. */
  int R_SI = 61;
  /** RegularExpression Id. */
  int R_SINO = 62;
  /** RegularExpression Id. */
  int R_SELECCIONA = 63;
  /** RegularExpression Id. */
  int R_CASO = 64;
  /** RegularExpression Id. */
  int R_DEFECTO = 65;
  /** RegularExpression Id. */
  int R_PARA = 66;
  /** RegularExpression Id. */
  int R_MIENTRAS = 67;
  /** RegularExpression Id. */
  int R_DETENER = 68;
  /** RegularExpression Id. */
  int R_FECHA = 69;
  /** RegularExpression Id. */
  int R_FECHA_HORA = 70;
  /** RegularExpression Id. */
  int R_CONTAR = 71;
  /** RegularExpression Id. */
  int R_TEXT = 72;
  /** RegularExpression Id. */
  int R_INTEGER = 73;
  /** RegularExpression Id. */
  int R_DOUBLE = 74;
  /** RegularExpression Id. */
  int R_BOOL = 75;
  /** RegularExpression Id. */
  int R_DATE = 76;
  /** RegularExpression Id. */
  int R_DATETIME = 77;
  /** RegularExpression Id. */
  int R_NO = 78;
  /** RegularExpression Id. */
  int R_NULO = 79;
  /** RegularExpression Id. */
  int R_AUTOINCREMENTABLE = 80;
  /** RegularExpression Id. */
  int R_PK = 81;
  /** RegularExpression Id. */
  int R_FK = 82;
  /** RegularExpression Id. */
  int R_UNICO = 83;
  /** RegularExpression Id. */
  int R_COMILLAS = 84;
  /** RegularExpression Id. */
  int ID = 85;
  /** RegularExpression Id. */
  int ENTERO = 86;
  /** RegularExpression Id. */
  int DECIMAL = 87;
  /** RegularExpression Id. */
  int CADENA = 88;
  /** RegularExpression Id. */
  int FECHA = 89;
  /** RegularExpression Id. */
  int FECHA_HORA = 90;
  /** RegularExpression Id. */
  int DOS_PUNTO = 91;
  /** RegularExpression Id. */
  int BOOLEAN = 92;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"USAR\"",
    "\"CREAR\"",
    "\"BASE_DATOS\"",
    "\"TABLA\"",
    "\"OBJETO\"",
    "\"PROCEDIMIENTO\"",
    "\"FUNCION\"",
    "\"RETORNO\"",
    "\"USUARIO\"",
    "\"COLOCAR\"",
    "\"password\"",
    "\"IMPRIMIR\"",
    "\"INSERTAR\"",
    "\"EN\"",
    "\"VALORES\"",
    "\"ACTUALIZAR\"",
    "\"DONDE\"",
    "\"BORRAR\"",
    "\"SELECCIONAR\"",
    "\"DE\"",
    "\"ORDENAR_POR\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"OTORGAR\"",
    "\"PERMISOS\"",
    "\"DENEGAR\"",
    "\"BACKUP\"",
    "\"USQLDUMP\"",
    "\"COMPLETO\"",
    "\"RESTAURAR\"",
    "\"ALTERAR\"",
    "\"AGREGAR\"",
    "\"QUITAR\"",
    "\"CAMBIAR\"",
    "\"ELIMINAR\"",
    "\"DECLARAR\"",
    "\"SI\"",
    "\"SINO\"",
    "\"SELECCIONA\"",
    "\"CASO\"",
    "\"DEFECTO\"",
    "\"PARA\"",
    "\"MIENTRAS\"",
    "\"DETENER\"",
    "\"FECHA\"",
    "\"FECHA_HORA\"",
    "\"CONTAR\"",
    "\"TEXT\"",
    "\"INTEGER\"",
    "\"DOUBLE\"",
    "\"BOOL\"",
    "\"DATE\"",
    "\"DATETIME\"",
    "\"No\"",
    "\"Nulo\"",
    "\"Autoincrementable\"",
    "\"Llave_Primaria\"",
    "\"Llave_Foranea\"",
    "\"Unico\"",
    "\"\\\"\"",
    "<ID>",
    "<ENTERO>",
    "<DECIMAL>",
    "<CADENA>",
    "<FECHA>",
    "<FECHA_HORA>",
    "\":\"",
    "<BOOLEAN>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "<token of kind 99>",
    "<token of kind 100>",
  };

}
