/* Generated By:JavaCC: Do not edit this line. AnalizadorTreeConstants.java Version 6.0_1 */
package Analizador;

public interface AnalizadorTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTINICIO = 1;
  public int JJTSENTENCIAS = 2;
  public int JJTSENTENCIA = 3;
  public int JJTUSAR = 4;
  public int JJTID = 5;
  public int JJTPUNTO_COMA = 6;
  public int JJTCREAR = 7;
  public int JJTOPCIONES_CREAR = 8;
  public int JJTC_BASE = 9;
  public int JJTC_TABLA = 10;
  public int JJTCAMPOS_TABLA = 11;
  public int JJTCAMPOS_TABLA_PRIMA = 12;
  public int JJTCAMPO_TABLA = 13;
  public int JJTCOMPLEMENTO = 14;
  public int JJTC_OBJETO = 15;
  public int JJTPARAMETROS = 16;
  public int JJTPARAMETRO = 17;
  public int JJTC_PRO = 18;
  public int JJTSUBSENTENCIA = 19;
  public int JJTC_FUNCION = 20;
  public int JJTSENTENCIAS_RETORNO = 21;
  public int JJTRETORNO = 22;
  public int JJTC_USUARIO = 23;
  public int JJTIMPRIMIR = 24;
  public int JJTINSERTAR = 25;
  public int JJTTIPO_INSERCION = 26;
  public int JJTCAMPOS = 27;
  public int JJTCAMPO = 28;
  public int JJTVALOR = 29;
  public int JJTACTUALIZAR = 30;
  public int JJTCONDICIONAR = 31;
  public int JJTBORRAR = 32;
  public int JJTSELECCIONAR = 33;
  public int JJTCAMPOS_SELECCION = 34;
  public int JJTORDENAMIENTO = 35;
  public int JJTMODO_ORDEN = 36;
  public int JJTOTORGAR = 37;
  public int JJTOBJETO = 38;
  public int JJTDENEGAR = 39;
  public int JJTBACK = 40;
  public int JJTTIPO_BACK = 41;
  public int JJTRESTAURAR = 42;
  public int JJTALTERAR = 43;
  public int JJTALTERADO = 44;
  public int JJTACCION_ALTERADO_TABLA = 45;
  public int JJTACCION_ALTERADO_OBJETO = 46;
  public int JJTELIMINAR = 47;
  public int JJTOBJETOS_ELIMINAR = 48;
  public int JJTDECLARAR = 49;
  public int JJTLISTA_VARIABLES = 50;
  public int JJTVARIABLE = 51;
  public int JJTASIGNACION_DECLARACION = 52;
  public int JJTASIGNACION = 53;
  public int JJTIF = 54;
  public int JJTSINO_ELSE = 55;
  public int JJTSWITCH = 56;
  public int JJTCASOS = 57;
  public int JJTCASO = 58;
  public int JJTSENTENCIAS_SWITHC = 59;
  public int JJTDEFECTO = 60;
  public int JJTFOR = 61;
  public int JJTDECLARACION_FOR = 62;
  public int JJTOPERADOR_FOR = 63;
  public int JJTWHILE = 64;
  public int JJTFECHA = 65;
  public int JJTFECHA_HORA = 66;
  public int JJTCONTAR = 67;
  public int JJTTIPO_DATO = 68;
  public int JJTLOGICA = 69;
  public int JJTLOG_OR = 70;
  public int JJTLOG_AND = 71;
  public int JJTRELACIONAL = 72;
  public int JJTRELACIONAL_PRIMA = 73;
  public int JJTSUB_RELACIONAL = 74;
  public int JJTARITMETICA = 75;
  public int JJTARITMETICA_PRIMA = 76;
  public int JJTMULTI_DIV = 77;
  public int JJTMULTI_DIV_PRIMA = 78;
  public int JJTPOTENCIAR = 79;
  public int JJTPOTENCIAR_PRIMA = 80;
  public int JJTUNARIO = 81;
  public int JJTEXPRESION = 82;
  public int JJTMENOS = 83;
  public int JJTENTERO = 84;
  public int JJTDECIMAL = 85;
  public int JJTCADENA = 86;
  public int JJTPROCEDIMIENTO = 87;
  public int JJTSUBSENTENCIAS = 88;
  public int JJTNOT = 89;
  public int JJTAND = 90;
  public int JJTOR = 91;
  public int JJTPAR_IZ = 92;
  public int JJTPAR_DER = 93;
  public int JJTIGUAL = 94;
  public int JJTDISTINTO = 95;
  public int JJTMENOR = 96;
  public int JJTMAYOR = 97;
  public int JJTMENOR_IGUAL = 98;
  public int JJTMAYOR_IGUAL = 99;
  public int JJTSUMA = 100;
  public int JJTMULTI = 101;
  public int JJTDIV = 102;
  public int JJTPOW = 103;
  public int JJTBOOLEAN = 104;
  public int JJTLOGICA_CONUSLTAS = 105;
  public int JJTOPERADOR_CONSULTA = 106;
  public int JJTOPERADOR_CONSULTA2 = 107;
  public int JJTLOGICA_CONUSLTAS2 = 108;
  public int JJTASC = 109;
  public int JJTDESC = 110;
  public int JJTUSQLDUMP = 111;
  public int JJTCOMPLETO = 112;
  public int JJTTABLA = 113;
  public int JJTUSUARIO = 114;
  public int JJTINCR = 115;
  public int JJTDECR = 116;
  public int JJTDETENER = 117;
  public int JJTBASE_DATOS = 118;
  public int JJTERROR_SKIPTO = 119;


  public String[] jjtNodeName = {
    "PROGRAMA",
    "inicio",
    "sentencias",
    "sentencia",
    "Usar",
    "ID",
    "PUNTO_COMA",
    "crear",
    "Opciones_Crear",
    "C_Base",
    "C_Tabla",
    "Campos_Tabla",
    "Campos_Tabla_prima",
    "Campo_Tabla",
    "COMPLEMENTO",
    "C_Objeto",
    "Parametros",
    "Parametro",
    "C_Pro",
    "SubSentencia",
    "C_Funcion",
    "Sentencias_Retorno",
    "Retorno",
    "C_Usuario",
    "Imprimir",
    "Insertar",
    "tipo_insercion",
    "campos",
    "campo",
    "Valor",
    "Actualizar",
    "Condicionar",
    "Borrar",
    "Seleccionar",
    "Campos_Seleccion",
    "Ordenamiento",
    "Modo_Orden",
    "Otorgar",
    "Objeto",
    "Denegar",
    "back",
    "tipo_back",
    "restaurar",
    "Alterar",
    "alterado",
    "accion_alterado_tabla",
    "accion_alterado_objeto",
    "Eliminar",
    "objetos_eliminar",
    "Declarar",
    "lista_variables",
    "variable",
    "asignacion_declaracion",
    "Asignacion",
    "IF",
    "sino_else",
    "Switch",
    "casos",
    "caso",
    "Sentencias_swithc",
    "defecto",
    "For",
    "declaracion_for",
    "operador_for",
    "While",
    "Fecha",
    "Fecha_Hora",
    "Contar",
    "TIPO_DATO",
    "logica",
    "log_or",
    "log_and",
    "relacional",
    "relacional_prima",
    "sub_relacional",
    "aritmetica",
    "aritmetica_prima",
    "multi_div",
    "multi_div_prima",
    "potenciar",
    "potenciar_prima",
    "unario",
    "Expresion",
    "Menos",
    "Entero",
    "DECIMAL",
    "CADENA",
    "Procedimiento",
    "SubSentencias",
    "NOT",
    "AND",
    "OR",
    "PAR_IZ",
    "PAR_DER",
    "IGUAL",
    "DISTINTO",
    "MENOR",
    "MAYOR",
    "MENOR_IGUAL",
    "MAYOR_IGUAL",
    "SUMA",
    "MULTI",
    "DIV",
    "POW",
    "BOOLEAN",
    "logica_Conusltas",
    "operador_consulta",
    "operador_consulta2",
    "logica_Conusltas2",
    "ASC",
    "DESC",
    "USQLDUMP",
    "COMPLETO",
    "TABLA",
    "USUARIO",
    "INCR",
    "DECR",
    "DETENER",
    "BASE_DATOS",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=52ee684a3f03ff1ca5a53f0c59ea1155 (do not edit this line) */
