/* Generated By:JavaCC: Do not edit this line. Analizador_PaquetesTreeConstants.java Version 6.0_1 */
package Analizador_Paquetes;

public interface Analizador_PaquetesTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTINICIO = 1;
  public int JJTLOGIN = 2;
  public int JJTVALIDAR = 3;
  public int JJTLOGIN_S = 4;
  public int JJTENTERO = 5;
  public int JJTINSTRUCCIONES = 6;
  public int JJTPAQUETE = 7;
  public int JJTTIPO_PAQUETE = 8;
  public int JJTP_USQL = 9;
  public int JJTP_REPORTE = 10;
  public int JJTFIN = 11;


  public String[] jjtNodeName = {
    "PROGRAMA",
    "inicio",
    "login",
    "validar",
    "login_S",
    "ENTERO",
    "INSTRUCCIONES",
    "paquete",
    "tipo_paquete",
    "p_usql",
    "p_reporte",
    "fin",
  };
}
/* JavaCC - OriginalChecksum=2c5f3db9b7c81e569fbd28136b8a6722 (do not edit this line) */
