/* Generated By:JJTree&JavaCC: Do not edit this line. Analizador_PaquetesConstants.java */
package Analizador_Paquetes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Analizador_PaquetesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ABRIR = 1;
  /** RegularExpression Id. */
  int CERRAR = 2;
  /** RegularExpression Id. */
  int R_VALIDAR = 3;
  /** RegularExpression Id. */
  int R_LOGIN = 4;
  /** RegularExpression Id. */
  int R_COMANDO = 5;
  /** RegularExpression Id. */
  int R_PAQUETE = 6;
  /** RegularExpression Id. */
  int R_INTRUCCION = 7;
  /** RegularExpression Id. */
  int R_USQL = 8;
  /** RegularExpression Id. */
  int R_REPORTE = 9;
  /** RegularExpression Id. */
  int R_FIN = 10;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 11;
  /** RegularExpression Id. */
  int COMA = 12;
  /** RegularExpression Id. */
  int COMILLAS = 13;
  /** RegularExpression Id. */
  int ENTERO = 14;
  /** RegularExpression Id. */
  int INSTRUCCIONES = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\"\\\"validar\\\"\"",
    "\"\\\"login\\\"\"",
    "\"\\\"comando\\\"\"",
    "\"\\\"paquete\\\"\"",
    "\"\\\"instruccion\\\"\"",
    "\"\\\"usql\\\"\"",
    "\"\\\"reporte\\\"\"",
    "\"\\\"fin\\\"\"",
    "\":\"",
    "\",\"",
    "\"\\\"\"",
    "<ENTERO>",
    "<INSTRUCCIONES>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
  };

}
