/* Generated By:JavaCC: Do not edit this line. SubAnalisisTreeConstants.java Version 6.0_1 */
package SubAnalisis;

public interface SubAnalisisTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTINICIO = 1;
  public int JJTSENTENCIA = 2;
  public int JJTUSAR = 3;
  public int JJTID = 4;
  public int JJTPUNTO_COMA = 5;
  public int JJTCREAR = 6;
  public int JJTOPCIONES_CREAR = 7;
  public int JJTC_BASE = 8;
  public int JJTC_TABLA = 9;
  public int JJTCAMPOS_TABLA = 10;
  public int JJTCAMPOS_TABLA_PRIMA = 11;
  public int JJTCAMPO_TABLA = 12;
  public int JJTCOMPLEMENTO = 13;
  public int JJTC_OBJETO = 14;
  public int JJTPARAMETROS = 15;
  public int JJTPARAMETRO = 16;
  public int JJTC_PRO = 17;
  public int JJTSUBSENTENCIA = 18;
  public int JJTC_FUNCION = 19;
  public int JJTSENTENCIAS_RETORNO = 20;
  public int JJTRETORNO = 21;
  public int JJTC_USUARIO = 22;
  public int JJTIMPRIMIR = 23;
  public int JJTINSERTAR = 24;
  public int JJTTIPO_INSERCION = 25;
  public int JJTCAMPOS = 26;
  public int JJTCAMPO = 27;
  public int JJTVALOR = 28;
  public int JJTACTUALIZAR = 29;
  public int JJTCONDICIONAR = 30;
  public int JJTBORRAR = 31;
  public int JJTSELECCIONAR = 32;
  public int JJTCAMPOS_SELECCION = 33;
  public int JJTORDENAMIENTO = 34;
  public int JJTMODO_ORDEN = 35;
  public int JJTOTORGAR = 36;
  public int JJTOBJETO = 37;
  public int JJTDENEGAR = 38;
  public int JJTBACK = 39;
  public int JJTTIPO_BACK = 40;
  public int JJTRESTAURAR = 41;
  public int JJTALTERAR = 42;
  public int JJTALTERADO = 43;
  public int JJTACCION_ALTERADO_TABLA = 44;
  public int JJTACCION_ALTERADO_OBJETO = 45;
  public int JJTELIMINAR = 46;
  public int JJTOBJETOS_ELIMINAR = 47;
  public int JJTDECLARAR = 48;
  public int JJTLISTA_VARIABLES = 49;
  public int JJTVARIABLE = 50;
  public int JJTASIGNACION_DECLARACION = 51;
  public int JJTASIGNACION = 52;
  public int JJTIF = 53;
  public int JJTSINO_ELSE = 54;
  public int JJTSWITCH = 55;
  public int JJTCASOS = 56;
  public int JJTCASO = 57;
  public int JJTSENTENCIAS_SWITHC = 58;
  public int JJTDEFECTO = 59;
  public int JJTFOR = 60;
  public int JJTDECLARACION_FOR = 61;
  public int JJTOPERADOR_FOR = 62;
  public int JJTWHILE = 63;
  public int JJTFECHA = 64;
  public int JJTFECHA_HORA = 65;
  public int JJTCONTAR = 66;
  public int JJTTIPO_DATO = 67;
  public int JJTLOGICA = 68;
  public int JJTLOG_OR = 69;
  public int JJTLOG_AND = 70;
  public int JJTRELACIONAL = 71;
  public int JJTRELACIONAL_PRIMA = 72;
  public int JJTSUB_RELACIONAL = 73;
  public int JJTARITMETICA = 74;
  public int JJTARITMETICA_PRIMA = 75;
  public int JJTMULTI_DIV = 76;
  public int JJTMULTI_DIV_PRIMA = 77;
  public int JJTPOTENCIAR = 78;
  public int JJTPOTENCIAR_PRIMA = 79;
  public int JJTUNARIO = 80;
  public int JJTEXPRESION = 81;
  public int JJTMENOS = 82;
  public int JJTENTERO = 83;
  public int JJTDECIMAL = 84;
  public int JJTCADENA = 85;
  public int JJTPROCEDIMIENTO = 86;
  public int JJTSUBSENTENCIAS = 87;
  public int JJTNOT = 88;
  public int JJTAND = 89;
  public int JJTOR = 90;
  public int JJTPAR_IZ = 91;
  public int JJTPAR_DER = 92;
  public int JJTIGUAL = 93;
  public int JJTDISTINTO = 94;
  public int JJTMENOR = 95;
  public int JJTMAYOR = 96;
  public int JJTMENOR_IGUAL = 97;
  public int JJTMAYOR_IGUAL = 98;
  public int JJTSUMA = 99;
  public int JJTMULTI = 100;
  public int JJTDIV = 101;
  public int JJTPOW = 102;
  public int JJTBOOLEAN = 103;
  public int JJTLOGICA_CONUSLTAS = 104;
  public int JJTOPERADOR_CONSULTA = 105;
  public int JJTOPERADOR_CONSULTA2 = 106;
  public int JJTLOGICA_CONUSLTAS2 = 107;
  public int JJTASC = 108;
  public int JJTDESC = 109;
  public int JJTUSQLDUMP = 110;
  public int JJTCOMPLETO = 111;
  public int JJTTABLA = 112;
  public int JJTUSUARIO = 113;
  public int JJTINCR = 114;
  public int JJTDECR = 115;
  public int JJTDETENER = 116;
  public int JJTERROR_SKIPTO = 117;


  public String[] jjtNodeName = {
    "PROGRAMA",
    "inicio",
    "sentencia",
    "Usar",
    "ID",
    "PUNTO_COMA",
    "crear",
    "Opciones_Crear",
    "C_Base",
    "C_Tabla",
    "Campos_Tabla",
    "Campos_Tabla_prima",
    "Campo_Tabla",
    "COMPLEMENTO",
    "C_Objeto",
    "Parametros",
    "Parametro",
    "C_Pro",
    "SubSentencia",
    "C_Funcion",
    "Sentencias_Retorno",
    "Retorno",
    "C_Usuario",
    "Imprimir",
    "Insertar",
    "tipo_insercion",
    "campos",
    "campo",
    "Valor",
    "Actualizar",
    "Condicionar",
    "Borrar",
    "Seleccionar",
    "Campos_Seleccion",
    "Ordenamiento",
    "Modo_Orden",
    "Otorgar",
    "Objeto",
    "Denegar",
    "back",
    "tipo_back",
    "restaurar",
    "Alterar",
    "alterado",
    "accion_alterado_tabla",
    "accion_alterado_objeto",
    "Eliminar",
    "objetos_eliminar",
    "Declarar",
    "lista_variables",
    "variable",
    "asignacion_declaracion",
    "Asignacion",
    "IF",
    "sino_else",
    "Switch",
    "casos",
    "caso",
    "Sentencias_swithc",
    "defecto",
    "For",
    "declaracion_for",
    "operador_for",
    "While",
    "Fecha",
    "Fecha_Hora",
    "Contar",
    "TIPO_DATO",
    "logica",
    "log_or",
    "log_and",
    "relacional",
    "relacional_prima",
    "sub_relacional",
    "aritmetica",
    "aritmetica_prima",
    "multi_div",
    "multi_div_prima",
    "potenciar",
    "potenciar_prima",
    "unario",
    "Expresion",
    "Menos",
    "Entero",
    "DECIMAL",
    "CADENA",
    "Procedimiento",
    "SubSentencias",
    "NOT",
    "AND",
    "OR",
    "PAR_IZ",
    "PAR_DER",
    "IGUAL",
    "DISTINTO",
    "MENOR",
    "MAYOR",
    "MENOR_IGUAL",
    "MAYOR_IGUAL",
    "SUMA",
    "MULTI",
    "DIV",
    "POW",
    "BOOLEAN",
    "logica_Conusltas",
    "operador_consulta",
    "operador_consulta2",
    "logica_Conusltas2",
    "ASC",
    "DESC",
    "USQLDUMP",
    "COMPLETO",
    "TABLA",
    "USUARIO",
    "INCR",
    "DECR",
    "DETENER",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=191c35fff89ede55617efd8fe9b6a0c2 (do not edit this line) */
