/* Generated By:JavaCC: Do not edit this line. Analizador_XMLTreeConstants.java Version 6.0_1 */
package Analizador_XML;

public interface Analizador_XMLTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTINICIO = 1;
  public int JJTMAESTRO = 2;
  public int JJTDB = 3;
  public int JJTBASE = 4;
  public int JJTTABB = 5;
  public int JJTPROCB = 6;
  public int JJTOBB = 7;
  public int JJTROWS = 8;
  public int JJTMETODOS = 9;
  public int JJTTIPOR = 10;
  public int JJTPARAMS = 11;
  public int JJTINTRUCCIONES = 12;
  public int JJTRETORNO = 13;
  public int JJTOBJETOS = 14;
  public int JJTATTRIBS = 15;
  public int JJTTIPO_DATO = 16;
  public int JJTATRIBUTOS = 17;
  public int JJTNOMBRE = 18;
  public int JJTRUTA = 19;
  public int JJTTABLA = 20;
  public int JJTROW = 21;
  public int JJTATRIBUTO = 22;


  public String[] jjtNodeName = {
    "PROGRAMA",
    "inicio",
    "maestro",
    "db",
    "base",
    "tabB",
    "procB",
    "obB",
    "rows",
    "metodos",
    "tipoR",
    "params",
    "intrucciones",
    "retorno",
    "objetos",
    "attribs",
    "TIPO_DATO",
    "atributos",
    "nombre",
    "ruta",
    "tabla",
    "row",
    "ATRIBUTO",
  };
}
/* JavaCC - OriginalChecksum=f95bf8d99587d2bd043517ac6a7b2b5b (do not edit this line) */
