/* Generated By:JJTree&JavaCC: Do not edit this line. Analizador_XMLConstants.java */
package Analizador_XML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Analizador_XMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAESTRO = 1;
  /** RegularExpression Id. */
  int C_MAESTRO = 2;
  /** RegularExpression Id. */
  int V_MAESTRO = 3;
  /** RegularExpression Id. */
  int DB = 4;
  /** RegularExpression Id. */
  int C_DB = 5;
  /** RegularExpression Id. */
  int BASE = 6;
  /** RegularExpression Id. */
  int C_BASE = 7;
  /** RegularExpression Id. */
  int V_BASE = 8;
  /** RegularExpression Id. */
  int OBJECT = 9;
  /** RegularExpression Id. */
  int C_OBJECT = 10;
  /** RegularExpression Id. */
  int PROCEDURE = 11;
  /** RegularExpression Id. */
  int C_PROCEDURE = 12;
  /** RegularExpression Id. */
  int TABLA = 13;
  /** RegularExpression Id. */
  int C_TABLA = 14;
  /** RegularExpression Id. */
  int V_TABLA = 15;
  /** RegularExpression Id. */
  int METODO = 16;
  /** RegularExpression Id. */
  int C_METODO = 17;
  /** RegularExpression Id. */
  int V_METODO = 18;
  /** RegularExpression Id. */
  int OBJETO = 19;
  /** RegularExpression Id. */
  int C_OBJETO = 20;
  /** RegularExpression Id. */
  int V_OBJETO = 21;
  /** RegularExpression Id. */
  int NOMBRE = 22;
  /** RegularExpression Id. */
  int C_NOMBRE = 23;
  /** RegularExpression Id. */
  int PROC = 24;
  /** RegularExpression Id. */
  int C_PROC = 25;
  /** RegularExpression Id. */
  int OBJ = 26;
  /** RegularExpression Id. */
  int C_OBJ = 27;
  /** RegularExpression Id. */
  int ATTR = 28;
  /** RegularExpression Id. */
  int C_ATTR = 29;
  /** RegularExpression Id. */
  int PARAMS = 30;
  /** RegularExpression Id. */
  int C_PARAMS = 31;
  /** RegularExpression Id. */
  int TIPO_RETURN = 32;
  /** RegularExpression Id. */
  int C_TIPO_RETURN = 33;
  /** RegularExpression Id. */
  int RETURN = 34;
  /** RegularExpression Id. */
  int C_RETURN = 35;
  /** RegularExpression Id. */
  int SRC = 36;
  /** RegularExpression Id. */
  int C_SRC = 37;
  /** RegularExpression Id. */
  int PATH = 38;
  /** RegularExpression Id. */
  int C_PATH = 39;
  /** RegularExpression Id. */
  int ROWS = 40;
  /** RegularExpression Id. */
  int C_ROWS = 41;
  /** RegularExpression Id. */
  int ROW = 42;
  /** RegularExpression Id. */
  int C_ROW = 43;
  /** RegularExpression Id. */
  int R_TEXT = 44;
  /** RegularExpression Id. */
  int R_INTEGER = 45;
  /** RegularExpression Id. */
  int R_DOUBLE = 46;
  /** RegularExpression Id. */
  int R_BOOL = 47;
  /** RegularExpression Id. */
  int R_DATE = 48;
  /** RegularExpression Id. */
  int R_DATETIME = 49;
  /** RegularExpression Id. */
  int R_ATRIBUTOS = 50;
  /** RegularExpression Id. */
  int IGUAL = 51;
  /** RegularExpression Id. */
  int INICIO = 52;
  /** RegularExpression Id. */
  int CIERRE = 53;
  /** RegularExpression Id. */
  int FIN = 54;
  /** RegularExpression Id. */
  int Atributo = 55;
  /** RegularExpression Id. */
  int ID = 56;
  /** RegularExpression Id. */
  int Propiedasdes = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<Maestro>\"",
    "\"</Maestro>\"",
    "\"<Maestro/>\"",
    "\"<DB>\"",
    "\"</DB>\"",
    "\"<Base>\"",
    "\"</Base>\"",
    "\"<Base/>\"",
    "\"<Object>\"",
    "\"</Object>\"",
    "\"<Procedure>\"",
    "\"</Procedure>\"",
    "\"<Tabla>\"",
    "\"</Tabla>\"",
    "\"<Tabla/>\"",
    "\"<Metodo>\"",
    "\"</Metodo>\"",
    "\"<Metodo/>\"",
    "\"<Objeto>\"",
    "\"</Objeto>\"",
    "\"<Objeto/>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<Proc>\"",
    "\"</Proc>\"",
    "\"<Obj>\"",
    "\"</Obj>\"",
    "\"<attr>\"",
    "\"</attr>\"",
    "\"<params>\"",
    "\"</params>\"",
    "\"<tipo_retorno>\"",
    "\"</tipo_retorno>\"",
    "\"<return>\"",
    "\"</return>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<Row>\"",
    "\"</Row>\"",
    "\"TEXT\"",
    "\"INTEGER\"",
    "\"DOUBLE\"",
    "\"BOOL\"",
    "\"DATE\"",
    "\"DATETIME\"",
    "\"Atributos\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "<Atributo>",
    "<ID>",
    "\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\" standalone=\\\"no\\\"?>\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
  };

}
